/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditStep {
  'title' : string,
  'description' : string,
  'stepNumber' : bigint,
}
export interface BlogPost {
  'title' : string,
  'date' : Time,
  'author' : string,
  'excerpt' : string,
  'category' : string,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Project {
  'title' : string,
  'description' : string,
  'category' : string,
}
export interface Service {
  'title' : string,
  'icon' : string,
  'description' : string,
}
export interface SiteStats {
  'yearsOfExperience' : bigint,
  'clientsServed' : bigint,
  'teamMembers' : bigint,
  'projectsCompleted' : bigint,
}
export interface TeamMember { 'bio' : string, 'name' : string, 'role' : string }
export type Time = bigint;
export interface _SERVICE {
  'addAuditStep' : ActorMethod<[string, string, bigint], undefined>,
  'addBlogPost' : ActorMethod<
    [string, string, string, Time, string],
    undefined
  >,
  'addProject' : ActorMethod<[string, string, string], undefined>,
  'addService' : ActorMethod<[string, string, string], undefined>,
  'addTeamMember' : ActorMethod<[string, string, string], undefined>,
  'getAllAuditSteps' : ActorMethod<[], Array<AuditStep>>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getSiteStats' : ActorMethod<[], SiteStats>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'updateSiteStats' : ActorMethod<[bigint, bigint, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];