/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AuditStep = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'stepNumber' : IDL.Nat,
});
export const BlogPost = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'author' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Service = IDL.Record({
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const SiteStats = IDL.Record({
  'yearsOfExperience' : IDL.Nat,
  'clientsServed' : IDL.Nat,
  'teamMembers' : IDL.Nat,
  'projectsCompleted' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addAuditStep' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text],
      [],
      [],
    ),
  'addProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addTeamMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllAuditSteps' : IDL.Func([], [IDL.Vec(AuditStep)], ['query']),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getSiteStats' : IDL.Func([], [SiteStats], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateSiteStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AuditStep = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'stepNumber' : IDL.Nat,
  });
  const BlogPost = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'author' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Service = IDL.Record({
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const SiteStats = IDL.Record({
    'yearsOfExperience' : IDL.Nat,
    'clientsServed' : IDL.Nat,
    'teamMembers' : IDL.Nat,
    'projectsCompleted' : IDL.Nat,
  });
  
  return IDL.Service({
    'addAuditStep' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text],
        [],
        [],
      ),
    'addProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addTeamMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllAuditSteps' : IDL.Func([], [IDL.Vec(AuditStep)], ['query']),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getSiteStats' : IDL.Func([], [SiteStats], ['query']),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateSiteStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };